[package]
name = "bindkey"
version = "0.1.0"
authors = ["Konstantin Zverev <object905@gmail.com>"]

[lib]
name = "bindkey"
path = "./src/lib.rs"

[dependencies]
fnv = "1.0"

[dependencies.x11]
version = "2.14"
features = ["xlib"]
